import type { CodegenConfig } from '@graphql-codegen/cli';

const eslintDisablePligin = {
  add: {
    content: [
      '/* eslint-disable */',
      '// WARNING: This file was automatically generated by graphql-code-generator and should not be edited.',
    ],
  },
};

const config: CodegenConfig = {
  schema: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  overwrite: true,
  documents: 'src/client/**/*.graphql',
  generates: {
    'src/client/shared/types/graphql.tsx': {
      plugins: [eslintDisablePligin, 'typescript'],
    },
    src: {
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.graphql-generated.ts',
        baseTypesPath: 'client/shared/types/graphql.tsx',
      },
      plugins: [
        eslintDisablePligin,
        'typescript-operations',
        'typescript-urql',
      ],
      hooks: {
        afterOneFileWrite: ['yarn prettify'],
      },
    },
  },
};

export default config;
